name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      id: login
      if: github.actor != 'dependabot[bot]'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      # only on push to main branch
      if: steps.login.outcome == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: hamidmayeli/sps:latest

    - name: Build and push Docker image
      # only on pull request
      if: steps.login.outcome == 'success' && github.event_name == 'pull_request'
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: hamidmayeli/sps:pr-${{ github.event.number }}
